%Main script for executing spot detection
%Blythe Hospelhorn
%Modified from code written by Ben Kesler & Gregor Neuert
%Version 1.0.0
%Updated Feb 18, 2021

%Update history
%   2021.02.18 | 1.0.0
%       Initial documentation
%   2021.08.31 | 1.1.0
%       Added parameter to turn off overwrite (ie. don't run if output
%       already exists and no overwrite)
%       Saves some run info to [outstem]_runinfo.mat

%%
% Run 3D spot detection on the provided image stack and output result
% tables to specified path.
%   This is designed to be callable from the commandline.
%
% ARGS
%   img_name (string) - Label for image, used in output file naming
%   inpath (string) - Path to input tiff image stack.
%   out_superdir (string) - Path to output directory (subdirectories will
%       be generated by this script)
%   chID (int) - Index of image channel to process.
%   chCount (int) - Total number of channels in input image.
%   t_min (int) - Minimum filter threshold to try (suggested: 1 if don't
%       know)
%   t_max (int) - Maximum filter threshold to try (suggested: 200-300)
%   dead_pix_detect (bool) - Whether to rerun dead pixel detection
%       (suggested: false)
%
% OUTPUTS
%   - 3D coordinate table (matlab format)
%   - Collapsed 2D coordinate table (matlab format)
%   - Table of spot counts vs. thresholds (2D and 3D, both matlab format)
%   - Scaled-down filtered max z projections of the input image with info
%       on how to scale the intensities for viewing (for downstream
%       visualization, matlab format)
%   - A copy of the 3D image filtered as a MATLAB matrix (matlab format)
%
%
function outstem = Main_RNASpotDetect(img_name, inpath, out_superdir, chID, chCount, ...
    t_min, t_max, dead_pix_detect, overwrite_output)

    %Load subdir into class path
    addpath('./core');
    
    strat = 'all_3d';
    
    %Set up paths
    outdir = [out_superdir filesep strat];
    outpath = [outdir filesep img_name '_' strat];
    outstem = outpath;
    if ~overwrite_output
        if isfile([outstem '_coordTable.mat'])
            fprintf("Spot detection output at %s already exists! Skipping spot detection...\n", outstem);
            return;
        end
    end
    mkdir(outdir);
    
    [stack, img_read] = tiffread2(inpath);
    Z = img_read/chCount;
    Y = size(stack(1,1).data,1);
    X = size(stack(1,1).data,2);

    img_ch_RNA = NaN(Y,X,Z);
    idx = chID;
    for z = 1:Z
        img_ch_RNA(:,:,z) = stack(1,idx).data;
        idx = idx + chCount;
    end
    
    %And run
    spotdec = RNA_Threshold_SpotDetector;
    spotdec.run_spot_detection(img_ch_RNA, outpath, strat, t_min, t_max, dead_pix_detect);
    
    img_info_path = [outstem '_runinfo'];
    idims = struct('x', X, 'y', Y, 'z', Z);
    save(img_info_path, 'img_name', 'inpath', 'out_superdir', 'chID', 'chCount', 't_min', 't_max', 'dead_pix_detect', 'idims');

end