%%
%%  !! UPDATE TO YOUR BASE DIR
ImgDir = 'D:\Users\hospelb\labdata\imgproc\imgproc';

% ========================== Image Channels ==========================

% run_count = 6;
% 
% i = run_count;
% % ---> mESC Set 2
% iruns(i) = struct('outdir', [ImgDir '\data\preprocess\feb2019\1Day\Tsix'],...
%     'imgname', 'mESC_1d_Tsix', 'ch_count', 4, 'rnach', 3, 'lightch', 4,...
%     'tifpath', [ImgDir '\img\mESC\20190218_1d_F1-2-1_Xist-CY5-Tsix-TMR_img_9_MMStack.ome.tif'],...
%     'cellseg_path', [ImgDir '\data\cell_seg\mESC\Lab_20190218_1d_F1-2-1_Xist-CY5-Tsix-TMR_img_9.mat']); i = i-1;
% iruns(i) = struct('outdir', [ImgDir '\data\preprocess\feb2019\1Day\Xist'],...
%     'imgname', 'mESC_1d_Xist', 'ch_count', 4, 'rnach', 2, 'lightch', 4,...
%     'tifpath', [ImgDir '\img\mESC\20190218_1d_F1-2-1_Xist-CY5-Tsix-TMR_img_9_MMStack.ome.tif'],...
%     'cellseg_path', [ImgDir '\data\cell_seg\mESC\Lab_20190218_1d_F1-2-1_Xist-CY5-Tsix-TMR_img_9.mat']); i = i-1;
% iruns(i) = struct('outdir', [ImgDir '\data\preprocess\feb2019\2Day\Tsix'],...
%     'imgname', 'mESC_2d_Tsix', 'ch_count', 4, 'rnach', 3, 'lightch', 4,...
%     'tifpath', [ImgDir '\img\mESC\20190220_2d_F1-2-1_Xist-CY5-Tsix-TMR_img_9_MMStack.ome.tif'],...
%     'cellseg_path', [ImgDir '\data\cell_seg\mESC\Lab_20190220_2d_F1-2-1_Xist-CY5-Tsix-TMR_img_9.mat']); i = i-1;
% iruns(i) = struct('outdir', [ImgDir '\data\preprocess\feb2019\2Day\Xist'],...
%     'imgname', 'mESC_2d_Xist', 'ch_count', 4, 'rnach', 2, 'lightch', 4,...
%     'tifpath', [ImgDir '\img\mESC\20190220_2d_F1-2-1_Xist-CY5-Tsix-TMR_img_9_MMStack.ome.tif'],...
%     'cellseg_path', [ImgDir '\data\cell_seg\mESC\Lab_20190220_2d_F1-2-1_Xist-CY5-Tsix-TMR_img_9.mat']); i = i-1;
% iruns(i) = struct('outdir', [ImgDir '\data\preprocess\feb2019\3Day\Tsix'],...
%     'imgname', 'mESC_3d_Tsix', 'ch_count', 4, 'rnach', 3, 'lightch', 4,...
%     'tifpath', [ImgDir '\img\mESC\20190221_3d_F1-2-1_Xist-CY5-Tsix-TMR_img_9_MMStack.ome.tif'],...
%     'cellseg_path', [ImgDir '\data\cell_seg\mESC\Lab_20190221_3d_F1-2-1_Xist-CY5-Tsix-TMR_img_9.mat']); i = i-1;
% iruns(i) = struct('outdir', [ImgDir '\data\preprocess\feb2019\3Day\Xist'],...
%     'imgname', 'mESC_3d_Xist', 'ch_count', 4, 'rnach', 2, 'lightch', 4,...
%     'tifpath', [ImgDir '\img\mESC\20190221_3d_F1-2-1_Xist-CY5-Tsix-TMR_img_9_MMStack.ome.tif'],...
%     'cellseg_path', [ImgDir '\data\cell_seg\mESC\Lab_20190221_3d_F1-2-1_Xist-CY5-Tsix-TMR_img_9.mat']); i = i-1;

% ---> Yeast RNA
run_count = 8;

i = run_count;
iruns(i) = struct('outdir', [ImgDir '\data\preprocess\YeastFISH\E1R2\STL1'],...
     'imgname', 'E1R2-STL1-TMR', 'ch_count', 4, 'rnach', 1, 'lightch', 4,...
     'tifpath', [ImgDir '\img\yeast\Exp1_rep2_10min_im4.tif'],...
     'cellseg_path', [ImgDir '\data\cell_seg\yeast\Lab_Exp1_rep2_10min_im4.mat'],...
     'probe_name', 'TMR', 'probe_targ', 'STL1'); i = i-1;
iruns(i) = struct('outdir', [ImgDir '\data\preprocess\YeastFISH\E1R2\CTT1'],...
     'imgname', 'E1R2-CTT1-CY5', 'ch_count', 4, 'rnach', 2, 'lightch', 4,...
     'tifpath', [ImgDir '\img\yeast\Exp1_rep2_10min_im4.tif'],...
     'cellseg_path', [ImgDir '\data\cell_seg\yeast\Lab_Exp1_rep2_10min_im4.mat'],...
     'probe_name', 'CY5', 'probe_targ', 'CTT1'); i = i-1;
iruns(i) = struct('outdir', [ImgDir '\data\preprocess\YeastFISH\E2R1\STL1'],...
     'imgname', 'E2R1-STL1-TMR', 'ch_count', 4, 'rnach', 1, 'lightch', 4,...
     'tifpath', [ImgDir '\img\yeast\Exp2_rep1_10min_im2.tif'],...
     'cellseg_path', [ImgDir '\data\cell_seg\yeast\Lab_Exp2_rep1_10min_im2.mat'],...
     'probe_name', 'TMR', 'probe_targ', 'STL1'); i = i-1;
iruns(i) = struct('outdir', [ImgDir '\data\preprocess\YeastFISH\E2R1\CTT1'],...
     'imgname', 'E2R1-CTT1-CY5', 'ch_count', 4, 'rnach', 2, 'lightch', 4,...
     'tifpath', [ImgDir '\img\yeast\Exp2_rep1_10min_im2.tif'],...
     'cellseg_path', [ImgDir '\data\cell_seg\yeast\Lab_Exp2_rep1_10min_im2.mat'],...
     'probe_name', 'CY5', 'probe_targ', 'CTT1'); i = i-1;
iruns(i) = struct('outdir', [ImgDir '\data\preprocess\YeastFISH\E2R2\Img3\STL1'],...
     'imgname', 'E2R2I3-STL1-TMR', 'ch_count', 4, 'rnach', 1, 'lightch', 4,...
     'tifpath', [ImgDir '\img\yeast\Exp2_rep2_10min_im3.tif'],...
     'cellseg_path', [ImgDir '\data\cell_seg\yeast\Lab_Exp2_rep2_10min_im3.mat'],...
     'probe_name', 'TMR', 'probe_targ', 'STL1'); i = i-1;
iruns(i) = struct('outdir', [ImgDir '\data\preprocess\YeastFISH\E2R2\Img3\CTT1'],...
     'imgname', 'E2R2I3-CTT1-CY5', 'ch_count', 4, 'rnach', 2, 'lightch', 4,...
     'tifpath', [ImgDir '\img\yeast\Exp2_rep2_10min_im3.tif'],...
     'cellseg_path', [ImgDir '\data\cell_seg\yeast\Lab_Exp2_rep2_10min_im3.mat'],...
     'probe_name', 'CY5', 'probe_targ', 'CTT1'); i = i-1;
iruns(i) = struct('outdir', [ImgDir '\data\preprocess\YeastFISH\E2R2\Img5\STL1'],...
     'imgname', 'E2R2I5-STL1-TMR', 'ch_count', 4, 'rnach', 1, 'lightch', 4,...
     'tifpath', [ImgDir '\img\yeast\Exp2_rep2_10min_im5.tif'],...
     'cellseg_path', [ImgDir '\data\cell_seg\yeast\Lab_Exp2_rep2_10min_im5.mat'],...
     'probe_name', 'TMR', 'probe_targ', 'STL1'); i = i-1;
iruns(i) = struct('outdir', [ImgDir '\data\preprocess\YeastFISH\E2R2\Img5\CTT1'],...
     'imgname', 'E2R2I5-CTT1-CY5', 'ch_count', 4, 'rnach', 2, 'lightch', 4,...
     'tifpath', [ImgDir '\img\yeast\Exp2_rep2_10min_im5.tif'],...
     'cellseg_path', [ImgDir '\data\cell_seg\yeast\Lab_Exp2_rep2_10min_im5.mat'],...
     'probe_name', 'CY5', 'probe_targ', 'CTT1'); i = i-1;

% ---> Yeast Protein
% run_count = 10;
% 
% i = run_count;
% iruns(i) = struct('outdir', [ImgDir '\data\preprocess\msb2\2M1m_img2'],...
%      'imgname', 'Msb2_02M_1m_img2_GFP', 'ch_count', 2, 'rnach', 1, 'lightch', 2,...
%      'tifpath', [ImgDir '\img\msb2\20180306_Msb2-GFP_02M_NaCl_1min_2_MMStack.ome.tif'],...
%      'cellseg_path', [], 'probe_name', 'GFP', 'probe_targ', 'Msb2'); i = i-1;
% iruns(i) = struct('outdir', [ImgDir '\data\preprocess\msb2\2M5m_img3'],...
%      'imgname', 'Msb2_02M_5m_img3_GFP', 'ch_count', 2, 'rnach', 1, 'lightch', 2,...
%      'tifpath', [ImgDir '\img\msb2\20180306_Msb2-GFP_02M_NaCl_5min_3_MMStack.ome.tif'],...
%      'cellseg_path', [], 'probe_name', 'GFP', 'probe_targ', 'Msb2'); i = i-1;
% iruns(i) = struct('outdir', [ImgDir '\data\preprocess\msb2\4M1m_img3'],...
%      'imgname', 'Msb2_04M_1m_img3_GFP', 'ch_count', 2, 'rnach', 1, 'lightch', 2,...
%      'tifpath', [ImgDir '\img\msb2\20180306_Msb2-GFP_04M_NaCl_1min_3_MMStack.ome.tif'],...
%      'cellseg_path', [], 'probe_name', 'GFP', 'probe_targ', 'Msb2'); i = i-1;
% iruns(i) = struct('outdir', [ImgDir '\data\preprocess\msb2\4M5m_img2'],...
%      'imgname', 'Msb2_04M_5m_img2_GFP', 'ch_count', 2, 'rnach', 1, 'lightch', 2,...
%      'tifpath', [ImgDir '\img\msb2\20180306_Msb2-GFP_04M_NaCl_5min_2_MMStack.ome.tif'],...
%      'cellseg_path', [], 'probe_name', 'GFP', 'probe_targ', 'Msb2'); i = i-1;
% iruns(i) = struct('outdir', [ImgDir '\data\preprocess\msb2\NoSalt_img1'],...
%      'imgname', 'Msb2_NoSalt_img1_GFP', 'ch_count', 2, 'rnach', 1, 'lightch', 2,...
%      'tifpath', [ImgDir '\img\msb2\20180306_Msb2-GFP_no_salt_1_MMStack.ome.tif'],...
%      'cellseg_path', [], 'probe_name', 'GFP', 'probe_targ', 'Msb2'); i = i-1;
% iruns(i) = struct('outdir', [ImgDir '\data\preprocess\opy2\2M1m_img3'],...
%      'imgname', 'Opy2_02M_1m_img3_GFP', 'ch_count', 2, 'rnach', 1, 'lightch', 2,...
%      'tifpath', [ImgDir '\img\opy2\20180306_Opy2-GFP_02M_NaCl_1min_3_MMStack.ome.tif'],...
%      'cellseg_path', [], 'probe_name', 'GFP', 'probe_targ', 'Opy2'); i = i-1;
% iruns(i) = struct('outdir', [ImgDir '\data\preprocess\opy2\2M5m_img2'],...
%      'imgname', 'Opy2_02M_5m_img2_GFP', 'ch_count', 2, 'rnach', 1, 'lightch', 2,...
%      'tifpath', [ImgDir '\img\opy2\20180306_Opy2-GFP_02M_NaCl_5min_2_MMStack.ome.tif'],...
%      'cellseg_path', [], 'probe_name', 'GFP', 'probe_targ', 'Opy2'); i = i-1;
% iruns(i) = struct('outdir', [ImgDir '\data\preprocess\opy2\4M1m_img1'],...
%      'imgname', 'Opy2_04M_1m_img1_GFP', 'ch_count', 2, 'rnach', 1, 'lightch', 2,...
%      'tifpath', [ImgDir '\img\opy2\20180306_Opy2-GFP_04M_NaCl_1min_1_MMStack.ome.tif'],...
%      'cellseg_path', [], 'probe_name', 'GFP', 'probe_targ', 'Opy2'); i = i-1;
% iruns(i) = struct('outdir', [ImgDir '\data\preprocess\opy2\4M5m_img3'],...
%      'imgname', 'Opy2_04M_5m_img3_GFP', 'ch_count', 2, 'rnach', 1, 'lightch', 2,...
%      'tifpath', [ImgDir '\img\opy2\20180306_Opy2-GFP_04M_NaCl_5min_3_MMStack.ome.tif'],...
%      'cellseg_path', [], 'probe_name', 'GFP', 'probe_targ', 'Opy2'); i = i-1;
% iruns(i) = struct('outdir', [ImgDir '\data\preprocess\opy2\NoSalt_img2'],...
%      'imgname', 'Opy2_NoSalt_img2_GFP', 'ch_count', 2, 'rnach', 1, 'lightch', 2,...
%      'tifpath', [ImgDir '\img\opy2\20180306_Opy2-GFP_no_salt_2_MMStack.ome.tif'],...
%      'cellseg_path', [], 'probe_name', 'GFP', 'probe_targ', 'Opy2'); i = i-1;


% ========================== Common Params ==========================

ctrl_path = [];
ctrl_ch = 0;
ctrl_ch_count = 0;

t_min = 1; 
t_max = 1000; 
z_trim = 1;

ttune_winsize = 15;
ttune_mad = -0.75;

species_name = 'Saccharomyces cerevisiae';
cell_name = 'BY4741';
target_mol = 'mRNA';
%target_mol = 'Protein';

% ========================== Iterate & Run ==========================

addpath('..');
for i = 1:run_count
    path_spotsrun = [iruns(i).outdir filesep iruns(i).imgname '_all_3d_rnaspotsrun.mat'];
    if isfile(path_spotsrun)
        spotsrun = RNASpotsRun.loadFrom(path_spotsrun);
        spotsrun.overwrite_output = false;
        RNA_Pipeline_Core(spotsrun, 1, []);
    else
        spotsrun = Main_RNASpots(iruns(i).imgname, iruns(i).tifpath, iruns(i).rnach, iruns(i).lightch,...
        iruns(i).ch_count, iruns(i).outdir, t_min, t_max, z_trim, iruns(i).cellseg_path, ctrl_path, ctrl_ch, ctrl_ch_count, ttune_winsize, ttune_mad, false);
    end
    
    %spotsrun = Main_RNASpots(iruns(i).imgname, iruns(i).tifpath, iruns(i).rnach, iruns(i).lightch,...
    %    iruns(i).ch_count, iruns(i).outdir, t_min, t_max, z_trim, iruns(i).cellseg_path, ctrl_path, ctrl_ch, ctrl_ch_count, ttune_winsize, ttune_mad, false);
    
    spotsrun.type_probe = iruns(i).probe_name;
    spotsrun.type_target = iruns(i).probe_targ;
    spotsrun.type_species = species_name;
    spotsrun.type_cell = cell_name;
    spotsrun.type_targetmol = target_mol;
    spotsrun.saveMe();
    
end
